import Foundation

/// For the moment, supported languages in Giphy
enum GiphySupportedLanguagesISO631: String, CaseIterable {
    case Arabic = "ar"
    case Bengali = "bn"
    case ChineseSimplified = "zh-CN"
    case ChineseTraditional = "zh-TW"
    case Czech = "cs"
    case Danish = "da"
    case Dutch = "nl"
    case English = "en"
    case Farsi = "fa"
    case Filipino = "tl"
    case Finnish = "fi"
    case French = "fr"
    case German = "de"
    case Hebrew = "he"
    case Hindi = "hi"
    case Hungarian = "hu"
    case Indonesian = "id"
    case Italian = "it"
    case Japanese = "ja"
    case Korean = "ko"
    case Malay = "ms"
    case Norwegian = "no"
    case Polish = "pl"
    case Portuguese = "pt"
    case Romanian = "ro"
    case Russian = "ru"
    case Spanish = "es"
    case Swedish = "sv"
    case Thai = "th"
    case Turkish = "tr"
    case Ukrainian = "uk"
    case Vietnamese = "vi"
}
